# Generated by Django 3.1.2 on 2020-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skintype',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
