# Generated by Django 3.1.2 on 2020-10-18 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0005_remove_product_writer'),
        ('user', '0002_auto_20201015_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skin.product'),
        ),
    ]
